version: "3.8"
services:
  service_1:
    container_name: service_1
    image: taps2003/service_1:latest
    build: ./service_1
    deploy:
      replicas: 1
  service_2:
    container_name: service_2
    image: taps2003/service_2:latest
    build: ./service_2
    deploy:
      replicas: 1
  service_3:
    container_name: service_3
    image: taps2003/service_3:latest
    build: ./service_3  
    deploy:
      replicas: 1
  service_4:
    container_name: service_4
    image: taps2003/service_4:latest
    build: ./service_4
    deploy:
      replicas: 1
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - "service_1"